database:
  type: sqlite
  database: dbname

  # Ignore if using SQLite
  host: localhost
  port: 3306
  user: admin
  password: password

SignIdentifier: [tshop]

PurchaseMessage: You purchased a ticket!

MaxPagesPerGui: 50

# Advanced Configuration Options

MaxStoredGuisPerPlayer: 50

DisableOnDatabaseModificationException: true

# No touch please
ConfigVersion: ${project.version}