database:
  host: localhost
  port: 3306
  database: dbname
  user: admin
  password: password

AllowGuiCreate: true
AllowGuiEdit: true
AllowGuiRename: true
AllowGuiDelete: true

AllowEditorAdd: true
AllowEditorRemove: true
AllowListGuiEditorsOtherOwners: true

AllowTicketCreate: true
AllowTicketRename: true

AllowLinkerCreate: true

AllowOpenShops: true

SignIdentifier: [tcgui]