database:
  host: localhost
  port: 3306
  database: dbname
  user: admin
  password: password

AllowGuiCreate: true
AllowGuiEdit: true
AllowGuiRename: true
AllowGuiDelete: true
AllowGuiSearchTickets: true
AllowGuiSearchLinkers: true
AllowGuiSetDisplayName: true
AllowGuiTransfer: true

AllowEditorAdd: true
AllowEditorRemove: true
AllowEditorRemoveAll: true
AllowListGuiEditorsOtherOwners: true

AllowTicketCreate: true
AllowTicketRename: true

AllowLinkerCreate: true
AllowLinkerRename: true
AllowLinkerSetDestinationPage: true

AllowOpenShops: true

SignIdentifier: [tcgui]

MaxStoredGuisPerPlayer: 50