database:
  type: sqlite
  database: dbname

  # Ignore if using SQLite
  host: localhost
  port: 3306
  user: admin
  password: password

DisableOnDatabaseModificationException: true

SignIdentifier: [tshop]

MaxPagesPerGui: 50

# Advanced Configuration Options

MaxStoredGuisPerPlayer: 50

# No touch please
ConfigVersion: ${project.version}