database:
  host: localhost
  port: 3306
  database: dbname
  user: admin
  password: password

AllowGuiCreate: true
AllowGuiEdit: true
AllowGuiRename: true
AllowGuiDelete: true

AllowListGuiEditorsOtherOwners: true

AllowTicketCreate: true

AllowOpenShops: true

