database:
  host: localhost
  port: 3306
  database: dbname
  user: admin
  password: password

SignIdentifier: [tshop]

MaxStoredGuisPerPlayer: 50

MaxPagesPerGui: 50

# No touch please
ConfigVersion: ${project.version}