on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven.
        run: mvn clean package
      - uses: actions/upload-artifact@v2
        with:
          name: Plugin
          path: target/tcgui*.jar
      - name: Publish Snapshot Release
        id: upload_assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/tcgui-*.jar
          asset_name: tcgui.jar
          tag: snapshot
          overwrite: true
          make_latest: false
          body: "Latest development build"
          release_name: Latest Development Build
